// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/project_layers/api_layer/data_source/login_data_source/login_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i19;
import 'dart:io' as _i34;

import 'package:flower_app/project_layers/api_layer/api_client/api_client.dart'
    as _i18;
import 'package:flower_app/project_layers/api_layer/models/categories_response.dart'
    as _i7;
import 'package:flower_app/project_layers/api_layer/models/get_all_notification_response_dto.dart'
    as _i12;
import 'package:flower_app/project_layers/api_layer/models/request/add_address_request_dto.dart'
    as _i35;
import 'package:flower_app/project_layers/api_layer/models/request/change_password_request_body.dart'
    as _i32;
import 'package:flower_app/project_layers/api_layer/models/request/forget_password_request_dto.dart'
    as _i27;
import 'package:flower_app/project_layers/api_layer/models/request/login_request.dart'
    as _i25;
import 'package:flower_app/project_layers/api_layer/models/request/reset_password_request_dto.dart'
    as _i31;
import 'package:flower_app/project_layers/api_layer/models/request/sign_up_request.dart'
    as _i24;
import 'package:flower_app/project_layers/api_layer/models/request/update_profile_request_dto.dart'
    as _i33;
import 'package:flower_app/project_layers/api_layer/models/request/verify_reset_code_request_dto.dart'
    as _i29;
import 'package:flower_app/project_layers/api_layer/models/response/address_response_dto.dart'
    as _i14;
import 'package:flower_app/project_layers/api_layer/models/response/best_seller_response.dart'
    as _i21;
import 'package:flower_app/project_layers/api_layer/models/response/best_seller_response_dto.dart'
    as _i22;
import 'package:flower_app/project_layers/api_layer/models/response/cart_response_dto.dart'
    as _i36;
import 'package:flower_app/project_layers/api_layer/models/response/category_response_dto.dart'
    as _i20;
import 'package:flower_app/project_layers/api_layer/models/response/change_password_response_dto.dart'
    as _i9;
import 'package:flower_app/project_layers/api_layer/models/response/forget_password_response_dto.dart'
    as _i26;
import 'package:flower_app/project_layers/api_layer/models/response/get_logged_user_data_response_dto.dart'
    as _i8;
import 'package:flower_app/project_layers/api_layer/models/response/login_response.dart'
    as _i6;
import 'package:flower_app/project_layers/api_layer/models/response/occasion_response_dto.dart'
    as _i23;
import 'package:flower_app/project_layers/api_layer/models/response/order_response.dart'
    as _i13;
import 'package:flower_app/project_layers/api_layer/models/response/reset_password_response_dto.dart'
    as _i30;
import 'package:flower_app/project_layers/api_layer/models/response/sign_up_response.dart'
    as _i5;
import 'package:flower_app/project_layers/api_layer/models/response/update_photo_response_dto.dart'
    as _i11;
import 'package:flower_app/project_layers/api_layer/models/response/update_profile_response_dto.dart'
    as _i10;
import 'package:flower_app/project_layers/api_layer/models/response/verify_reset_code_response.dart'
    as _i28;
import 'package:flower_app/project_layers/data_layer/model/occasions_response.dart'
    as _i2;
import 'package:flower_app/project_layers/data_layer/model/products_response.dart'
    as _i3;
import 'package:flower_app/project_layers/presentaion_layer/checkout/data/model/get_user_addreses_respone/get_user_addreses_respone.dart'
    as _i15;
import 'package:flower_app/project_layers/presentaion_layer/payment/data/model/request/payment_request_model_dto.dart'
    as _i37;
import 'package:flower_app/project_layers/presentaion_layer/payment/data/model/responce/card_pay_responce/card_pay_responce_model_dto.dart'
    as _i16;
import 'package:flower_app/project_layers/presentaion_layer/payment/data/model/responce/cash_pay_responce/cash_pay_responce_model_dto.dart'
    as _i17;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOccasionsResponse_0 extends _i1.SmartFake
    implements _i2.OccasionsResponse {
  _FakeOccasionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponse_1 extends _i1.SmartFake
    implements _i3.ProductsResponse {
  _FakeProductsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_2<T> extends _i1.SmartFake
    implements _i4.HttpResponse<T> {
  _FakeHttpResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignUpResponse_3 extends _i1.SmartFake
    implements _i5.SignUpResponse {
  _FakeSignUpResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_4 extends _i1.SmartFake implements _i6.LoginResponse {
  _FakeLoginResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_5 extends _i1.SmartFake
    implements _i7.CategoriesResponse {
  _FakeCategoriesResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetLoggedUserDataResponseDto_6 extends _i1.SmartFake
    implements _i8.GetLoggedUserDataResponseDto {
  _FakeGetLoggedUserDataResponseDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_7 extends _i1.SmartFake
    implements _i9.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileResponseDto_8 extends _i1.SmartFake
    implements _i10.UpdateProfileResponseDto {
  _FakeUpdateProfileResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdatePhotoResponseDto_9 extends _i1.SmartFake
    implements _i11.UpdatePhotoResponseDto {
  _FakeUpdatePhotoResponseDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllNotificationResponseDto_10 extends _i1.SmartFake
    implements _i12.GetAllNotificationResponseDto {
  _FakeGetAllNotificationResponseDto_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeOrderResponse_11 extends _i1.SmartFake
    implements _i13.OrderResponse {
  _FakeOrderResponse_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAddressResponseDto_12 extends _i1.SmartFake
    implements _i14.AddressResponseDto {
  _FakeAddressResponseDto_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserAddresesRespone_13 extends _i1.SmartFake
    implements _i15.GetUserAddresesRespone {
  _FakeGetUserAddresesRespone_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCardPayResponceModelDto_14 extends _i1.SmartFake
    implements _i16.CardPayResponceModelDto {
  _FakeCardPayResponceModelDto_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCashPayResponceModelDto_15 extends _i1.SmartFake
    implements _i17.CashPayResponceModelDto {
  _FakeCashPayResponceModelDto_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i18.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.Future<_i2.OccasionsResponse> getOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, []),
            returnValue: _i19.Future<_i2.OccasionsResponse>.value(
              _FakeOccasionsResponse_0(
                this,
                Invocation.method(#getOccasions, []),
              ),
            ),
          )
          as _i19.Future<_i2.OccasionsResponse>);

  @override
  _i19.Future<_i3.ProductsResponse> getProductsById(String? occasionId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsById, [occasionId]),
            returnValue: _i19.Future<_i3.ProductsResponse>.value(
              _FakeProductsResponse_1(
                this,
                Invocation.method(#getProductsById, [occasionId]),
              ),
            ),
          )
          as _i19.Future<_i3.ProductsResponse>);

  @override
  _i19.Future<_i4.HttpResponse<_i20.CategoryResponseDto>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i20.CategoryResponseDto>>.value(
                  _FakeHttpResponse_2<_i20.CategoryResponseDto>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i20.CategoryResponseDto>>);

  @override
  _i19.Future<_i4.HttpResponse<_i21.BestSellerResponse>>
  getBestSellersProduct() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSellersProduct, []),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i21.BestSellerResponse>>.value(
                  _FakeHttpResponse_2<_i21.BestSellerResponse>(
                    this,
                    Invocation.method(#getBestSellersProduct, []),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i21.BestSellerResponse>>);

  @override
  _i19.Future<_i4.HttpResponse<_i22.BestSellerResponseDto>> getBestSellers() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSellers, []),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i22.BestSellerResponseDto>>.value(
                  _FakeHttpResponse_2<_i22.BestSellerResponseDto>(
                    this,
                    Invocation.method(#getBestSellers, []),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i22.BestSellerResponseDto>>);

  @override
  _i19.Future<_i4.HttpResponse<_i23.OccasionResponseDto>> getOccasionss() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasionss, []),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i23.OccasionResponseDto>>.value(
                  _FakeHttpResponse_2<_i23.OccasionResponseDto>(
                    this,
                    Invocation.method(#getOccasionss, []),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i23.OccasionResponseDto>>);

  @override
  _i19.Future<_i5.SignUpResponse> signUp(
    _i24.SignUpRequestBody? signUpRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpRequest]),
            returnValue: _i19.Future<_i5.SignUpResponse>.value(
              _FakeSignUpResponse_3(
                this,
                Invocation.method(#signUp, [signUpRequest]),
              ),
            ),
          )
          as _i19.Future<_i5.SignUpResponse>);

  @override
  _i19.Future<_i6.LoginResponse> login({required _i25.LoginRequest? request}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#request: request}),
            returnValue: _i19.Future<_i6.LoginResponse>.value(
              _FakeLoginResponse_4(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
          )
          as _i19.Future<_i6.LoginResponse>);

  @override
  _i19.Future<_i4.HttpResponse<_i26.ForgetPasswordResponseDto>> forgetPassword({
    required _i27.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue:
                _i19.Future<
                  _i4.HttpResponse<_i26.ForgetPasswordResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i26.ForgetPasswordResponseDto>(
                    this,
                    Invocation.method(#forgetPassword, [], {
                      #forgetPasswordRequestDto: forgetPasswordRequestDto,
                    }),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i26.ForgetPasswordResponseDto>>);

  @override
  _i19.Future<_i4.HttpResponse<_i28.VerifyResetCodeResponseDto>>
  verifyResetCode({
    required _i29.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue:
                _i19.Future<
                  _i4.HttpResponse<_i28.VerifyResetCodeResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i28.VerifyResetCodeResponseDto>(
                    this,
                    Invocation.method(#verifyResetCode, [], {
                      #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                    }),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i28.VerifyResetCodeResponseDto>>);

  @override
  _i19.Future<_i4.HttpResponse<_i30.ResetPasswordResponseDto>> resetPassword({
    required _i31.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue:
                _i19.Future<
                  _i4.HttpResponse<_i30.ResetPasswordResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i30.ResetPasswordResponseDto>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #resetPasswordRequestDto: resetPasswordRequestDto,
                    }),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i30.ResetPasswordResponseDto>>);

  @override
  _i19.Future<_i7.CategoriesResponse> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i19.Future<_i7.CategoriesResponse>.value(
              _FakeCategoriesResponse_5(
                this,
                Invocation.method(#getAllCategories, []),
              ),
            ),
          )
          as _i19.Future<_i7.CategoriesResponse>);

  @override
  _i19.Future<_i3.ProductsResponse> getProductsByIdF(
    Map<String, dynamic>? filters,
    String? search,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByIdF, [filters, search]),
            returnValue: _i19.Future<_i3.ProductsResponse>.value(
              _FakeProductsResponse_1(
                this,
                Invocation.method(#getProductsByIdF, [filters, search]),
              ),
            ),
          )
          as _i19.Future<_i3.ProductsResponse>);

  @override
  _i19.Future<_i8.GetLoggedUserDataResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserData, []),
            returnValue: _i19.Future<_i8.GetLoggedUserDataResponseDto>.value(
              _FakeGetLoggedUserDataResponseDto_6(
                this,
                Invocation.method(#getLoggedUserData, []),
              ),
            ),
          )
          as _i19.Future<_i8.GetLoggedUserDataResponseDto>);

  @override
  _i19.Future<_i9.ChangePasswordResponseDto> changePassword(
    _i32.ChangePasswordRequestBody? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i19.Future<_i9.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_7(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i19.Future<_i9.ChangePasswordResponseDto>);

  @override
  _i19.Future<_i10.UpdateProfileResponseDto> editProfile(
    _i33.UpdateProfileRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i19.Future<_i10.UpdateProfileResponseDto>.value(
              _FakeUpdateProfileResponseDto_8(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i19.Future<_i10.UpdateProfileResponseDto>);

  @override
  _i19.Future<_i11.UpdatePhotoResponseDto> changePhoto(_i34.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#changePhoto, [photo]),
            returnValue: _i19.Future<_i11.UpdatePhotoResponseDto>.value(
              _FakeUpdatePhotoResponseDto_9(
                this,
                Invocation.method(#changePhoto, [photo]),
              ),
            ),
          )
          as _i19.Future<_i11.UpdatePhotoResponseDto>);

  @override
  _i19.Future<_i12.GetAllNotificationResponseDto> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i19.Future<_i12.GetAllNotificationResponseDto>.value(
              _FakeGetAllNotificationResponseDto_10(
                this,
                Invocation.method(#getNotifications, []),
              ),
            ),
          )
          as _i19.Future<_i12.GetAllNotificationResponseDto>);

  @override
  _i19.Future<_i13.OrderResponse> orders() =>
      (super.noSuchMethod(
            Invocation.method(#orders, []),
            returnValue: _i19.Future<_i13.OrderResponse>.value(
              _FakeOrderResponse_11(this, Invocation.method(#orders, [])),
            ),
          )
          as _i19.Future<_i13.OrderResponse>);

  @override
  _i19.Future<_i14.AddressResponseDto> addAddresses(
    _i35.AddAddressRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAddresses, [request]),
            returnValue: _i19.Future<_i14.AddressResponseDto>.value(
              _FakeAddressResponseDto_12(
                this,
                Invocation.method(#addAddresses, [request]),
              ),
            ),
          )
          as _i19.Future<_i14.AddressResponseDto>);

  @override
  _i19.Future<_i14.AddressResponseDto> getAllAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAddresses, []),
            returnValue: _i19.Future<_i14.AddressResponseDto>.value(
              _FakeAddressResponseDto_12(
                this,
                Invocation.method(#getAllAddresses, []),
              ),
            ),
          )
          as _i19.Future<_i14.AddressResponseDto>);

  @override
  _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>> addToCart(
    Map<String, dynamic>? body,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addToCart, [body, token]),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>>.value(
                  _FakeHttpResponse_2<_i36.CartResponseDto>(
                    this,
                    Invocation.method(#addToCart, [body, token]),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>>);

  @override
  _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>> getCart(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getCart, [token]),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>>.value(
                  _FakeHttpResponse_2<_i36.CartResponseDto>(
                    this,
                    Invocation.method(#getCart, [token]),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>>);

  @override
  _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>> deleteItemFromCart(
    String? itemId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItemFromCart, [itemId, token]),
            returnValue:
                _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>>.value(
                  _FakeHttpResponse_2<_i36.CartResponseDto>(
                    this,
                    Invocation.method(#deleteItemFromCart, [itemId, token]),
                  ),
                ),
          )
          as _i19.Future<_i4.HttpResponse<_i36.CartResponseDto>>);

  @override
  _i19.Future<_i15.GetUserAddresesRespone> getLoggedUserAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserAddresses, []),
            returnValue: _i19.Future<_i15.GetUserAddresesRespone>.value(
              _FakeGetUserAddresesRespone_13(
                this,
                Invocation.method(#getLoggedUserAddresses, []),
              ),
            ),
          )
          as _i19.Future<_i15.GetUserAddresesRespone>);

  @override
  _i19.Future<_i16.CardPayResponceModelDto> paymentCard(
    _i37.PaymentRequestModelDto? paymentRequestModelDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#paymentCard, [paymentRequestModelDto]),
            returnValue: _i19.Future<_i16.CardPayResponceModelDto>.value(
              _FakeCardPayResponceModelDto_14(
                this,
                Invocation.method(#paymentCard, [paymentRequestModelDto]),
              ),
            ),
          )
          as _i19.Future<_i16.CardPayResponceModelDto>);

  @override
  _i19.Future<_i17.CashPayResponceModelDto> paymentCash(
    _i37.PaymentRequestModelDto? paymentRequestModelDto,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#paymentCash, [paymentRequestModelDto]),
            returnValue: _i19.Future<_i17.CashPayResponceModelDto>.value(
              _FakeCashPayResponceModelDto_15(
                this,
                Invocation.method(#paymentCash, [paymentRequestModelDto]),
              ),
            ),
          )
          as _i19.Future<_i17.CashPayResponceModelDto>);
}
