// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzx8MWW-WsH85_C3mD0dvpVTWK-iaYWTw',
    appId: '1:833128608721:android:eaf8249c5c59d1d316a6f0',
    messagingSenderId: '833128608721',
    projectId: 'tracking-app-bf231',
    storageBucket: 'tracking-app-bf231.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg32jkIOo9URzxwh4O8hulxmhjkPSX6yI',
    appId: '1:833128608721:ios:0845eb3689b60fef16a6f0',
    messagingSenderId: '833128608721',
    projectId: 'tracking-app-bf231',
    storageBucket: 'tracking-app-bf231.firebasestorage.app',
    iosBundleId: 'com.example.flowerApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWMBmkrza9f9V2A5SQzZAj7ELdqottges',
    appId: '1:833128608721:web:280734e3bf508a5e16a6f0',
    messagingSenderId: '833128608721',
    projectId: 'tracking-app-bf231',
    authDomain: 'tracking-app-bf231.firebaseapp.com',
    storageBucket: 'tracking-app-bf231.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWMBmkrza9f9V2A5SQzZAj7ELdqottges',
    appId: '1:833128608721:web:f2e98bb04e54376f16a6f0',
    messagingSenderId: '833128608721',
    projectId: 'tracking-app-bf231',
    authDomain: 'tracking-app-bf231.firebaseapp.com',
    storageBucket: 'tracking-app-bf231.firebasestorage.app',
  );

}