// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/project_layers/api_layer/data_sources_impl/sign_up_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flower_app/project_layers/api_layer/api_client/api_client.dart'
    as _i5;
import 'package:flower_app/project_layers/api_layer/models/request/forget_password_request_dto.dart'
    as _i10;
import 'package:flower_app/project_layers/api_layer/models/request/login_request.dart'
    as _i8;
import 'package:flower_app/project_layers/api_layer/models/request/reset_password_request_dto.dart'
    as _i14;
import 'package:flower_app/project_layers/api_layer/models/request/sign_up_request.dart'
    as _i7;
import 'package:flower_app/project_layers/api_layer/models/request/verify_reset_code_request_dto.dart'
    as _i12;
import 'package:flower_app/project_layers/api_layer/models/response/forget_password_response_dto.dart'
    as _i9;
import 'package:flower_app/project_layers/api_layer/models/response/login_response.dart'
    as _i3;
import 'package:flower_app/project_layers/api_layer/models/response/reset_password_response_dto.dart'
    as _i13;
import 'package:flower_app/project_layers/api_layer/models/response/sign_up_response.dart'
    as _i2;
import 'package:flower_app/project_layers/api_layer/models/response/verify_reset_code_response.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResponse_0 extends _i1.SmartFake
    implements _i2.SignUpResponse {
  _FakeSignUpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_2<T> extends _i1.SmartFake
    implements _i4.HttpResponse<T> {
  _FakeHttpResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.SignUpResponse> signUp(_i7.SignUpRequestBody? signUpRequest) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpRequest]),
            returnValue: _i6.Future<_i2.SignUpResponse>.value(
              _FakeSignUpResponse_0(
                this,
                Invocation.method(#signUp, [signUpRequest]),
              ),
            ),
          )
          as _i6.Future<_i2.SignUpResponse>);

  @override
  _i6.Future<_i3.LoginResponse> login({required _i8.LoginRequest? request}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#request: request}),
            returnValue: _i6.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
          )
          as _i6.Future<_i3.LoginResponse>);

  @override
  _i6.Future<_i4.HttpResponse<_i9.ForgetPasswordResponseDto>> forgetPassword({
    required _i10.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue:
                _i6.Future<
                  _i4.HttpResponse<_i9.ForgetPasswordResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i9.ForgetPasswordResponseDto>(
                    this,
                    Invocation.method(#forgetPassword, [], {
                      #forgetPasswordRequestDto: forgetPasswordRequestDto,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.HttpResponse<_i9.ForgetPasswordResponseDto>>);

  @override
  _i6.Future<_i4.HttpResponse<_i11.VerifyResetCodeResponseDto>>
  verifyResetCode({
    required _i12.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue:
                _i6.Future<
                  _i4.HttpResponse<_i11.VerifyResetCodeResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i11.VerifyResetCodeResponseDto>(
                    this,
                    Invocation.method(#verifyResetCode, [], {
                      #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.HttpResponse<_i11.VerifyResetCodeResponseDto>>);

  @override
  _i6.Future<_i4.HttpResponse<_i13.ResetPasswordResponseDto>> resetPassword({
    required _i14.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue:
                _i6.Future<
                  _i4.HttpResponse<_i13.ResetPasswordResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i13.ResetPasswordResponseDto>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #resetPasswordRequestDto: resetPasswordRequestDto,
                    }),
                  ),
                ),
          )
          as _i6.Future<_i4.HttpResponse<_i13.ResetPasswordResponseDto>>);
}
