// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/project_layers/api_layer/data_sources_impl/sign_up_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i15;
import 'dart:io' as _i30;

import 'package:flower_app/project_layers/api_layer/api_client/api_client.dart'
    as _i14;
import 'package:flower_app/project_layers/api_layer/models/categories_response.dart'
    as _i7;
import 'package:flower_app/project_layers/api_layer/models/get_all_notification_response_dto.dart'
    as _i12;
import 'package:flower_app/project_layers/api_layer/models/request/add_address_request_dto.dart'
    as _i31;
import 'package:flower_app/project_layers/api_layer/models/request/change_password_request_body.dart'
    as _i28;
import 'package:flower_app/project_layers/api_layer/models/request/forget_password_request_dto.dart'
    as _i23;
import 'package:flower_app/project_layers/api_layer/models/request/login_request.dart'
    as _i21;
import 'package:flower_app/project_layers/api_layer/models/request/reset_password_request_dto.dart'
    as _i27;
import 'package:flower_app/project_layers/api_layer/models/request/sign_up_request.dart'
    as _i20;
import 'package:flower_app/project_layers/api_layer/models/request/update_profile_request_dto.dart'
    as _i29;
import 'package:flower_app/project_layers/api_layer/models/request/verify_reset_code_request_dto.dart'
    as _i25;
import 'package:flower_app/project_layers/api_layer/models/response/address_response_dto.dart'
    as _i13;
import 'package:flower_app/project_layers/api_layer/models/response/best_seller_response.dart'
    as _i17;
import 'package:flower_app/project_layers/api_layer/models/response/best_seller_response_dto.dart'
    as _i18;
import 'package:flower_app/project_layers/api_layer/models/response/category_response_dto.dart'
    as _i16;
import 'package:flower_app/project_layers/api_layer/models/response/change_password_response_dto.dart'
    as _i9;
import 'package:flower_app/project_layers/api_layer/models/response/forget_password_response_dto.dart'
    as _i22;
import 'package:flower_app/project_layers/api_layer/models/response/get_logged_user_data_response_dto.dart'
    as _i8;
import 'package:flower_app/project_layers/api_layer/models/response/login_response.dart'
    as _i6;
import 'package:flower_app/project_layers/api_layer/models/response/occasion_response_dto.dart'
    as _i19;
import 'package:flower_app/project_layers/api_layer/models/response/reset_password_response_dto.dart'
    as _i26;
import 'package:flower_app/project_layers/api_layer/models/response/sign_up_response.dart'
    as _i5;
import 'package:flower_app/project_layers/api_layer/models/response/update_photo_response_dto.dart'
    as _i11;
import 'package:flower_app/project_layers/api_layer/models/response/update_profile_response_dto.dart'
    as _i10;
import 'package:flower_app/project_layers/api_layer/models/response/verify_reset_code_response.dart'
    as _i24;
import 'package:flower_app/project_layers/data_layer/model/occasions_response.dart'
    as _i2;
import 'package:flower_app/project_layers/data_layer/model/products_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOccasionsResponse_0 extends _i1.SmartFake
    implements _i2.OccasionsResponse {
  _FakeOccasionsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsResponse_1 extends _i1.SmartFake
    implements _i3.ProductsResponse {
  _FakeProductsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_2<T> extends _i1.SmartFake
    implements _i4.HttpResponse<T> {
  _FakeHttpResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignUpResponse_3 extends _i1.SmartFake
    implements _i5.SignUpResponse {
  _FakeSignUpResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_4 extends _i1.SmartFake implements _i6.LoginResponse {
  _FakeLoginResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_5 extends _i1.SmartFake
    implements _i7.CategoriesResponse {
  _FakeCategoriesResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetLoggedUserDataResponseDto_6 extends _i1.SmartFake
    implements _i8.GetLoggedUserDataResponseDto {
  _FakeGetLoggedUserDataResponseDto_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeChangePasswordResponseDto_7 extends _i1.SmartFake
    implements _i9.ChangePasswordResponseDto {
  _FakeChangePasswordResponseDto_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileResponseDto_8 extends _i1.SmartFake
    implements _i10.UpdateProfileResponseDto {
  _FakeUpdateProfileResponseDto_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdatePhotoResponseDto_9 extends _i1.SmartFake
    implements _i11.UpdatePhotoResponseDto {
  _FakeUpdatePhotoResponseDto_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAllNotificationResponseDto_10 extends _i1.SmartFake
    implements _i12.GetAllNotificationResponseDto {
  _FakeGetAllNotificationResponseDto_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeAddressResponseDto_11 extends _i1.SmartFake
    implements _i13.AddressResponseDto {
  _FakeAddressResponseDto_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i14.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i15.Future<_i2.OccasionsResponse> getOccasions() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasions, []),
            returnValue: _i15.Future<_i2.OccasionsResponse>.value(
              _FakeOccasionsResponse_0(
                this,
                Invocation.method(#getOccasions, []),
              ),
            ),
          )
          as _i15.Future<_i2.OccasionsResponse>);

  @override
  _i15.Future<_i3.ProductsResponse> getProductsById(String? occasionId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsById, [occasionId]),
            returnValue: _i15.Future<_i3.ProductsResponse>.value(
              _FakeProductsResponse_1(
                this,
                Invocation.method(#getProductsById, [occasionId]),
              ),
            ),
          )
          as _i15.Future<_i3.ProductsResponse>);

  @override
  _i15.Future<_i4.HttpResponse<_i16.CategoryResponseDto>> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue:
                _i15.Future<_i4.HttpResponse<_i16.CategoryResponseDto>>.value(
                  _FakeHttpResponse_2<_i16.CategoryResponseDto>(
                    this,
                    Invocation.method(#getCategories, []),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i16.CategoryResponseDto>>);

  @override
  _i15.Future<_i4.HttpResponse<_i17.BestSellerResponse>>
  getBestSellersProduct() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSellersProduct, []),
            returnValue:
                _i15.Future<_i4.HttpResponse<_i17.BestSellerResponse>>.value(
                  _FakeHttpResponse_2<_i17.BestSellerResponse>(
                    this,
                    Invocation.method(#getBestSellersProduct, []),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i17.BestSellerResponse>>);

  @override
  _i15.Future<_i4.HttpResponse<_i18.BestSellerResponseDto>> getBestSellers() =>
      (super.noSuchMethod(
            Invocation.method(#getBestSellers, []),
            returnValue:
                _i15.Future<_i4.HttpResponse<_i18.BestSellerResponseDto>>.value(
                  _FakeHttpResponse_2<_i18.BestSellerResponseDto>(
                    this,
                    Invocation.method(#getBestSellers, []),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i18.BestSellerResponseDto>>);

  @override
  _i15.Future<_i4.HttpResponse<_i19.OccasionResponseDto>> getOccasionss() =>
      (super.noSuchMethod(
            Invocation.method(#getOccasionss, []),
            returnValue:
                _i15.Future<_i4.HttpResponse<_i19.OccasionResponseDto>>.value(
                  _FakeHttpResponse_2<_i19.OccasionResponseDto>(
                    this,
                    Invocation.method(#getOccasionss, []),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i19.OccasionResponseDto>>);

  @override
  _i15.Future<_i5.SignUpResponse> signUp(
    _i20.SignUpRequestBody? signUpRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpRequest]),
            returnValue: _i15.Future<_i5.SignUpResponse>.value(
              _FakeSignUpResponse_3(
                this,
                Invocation.method(#signUp, [signUpRequest]),
              ),
            ),
          )
          as _i15.Future<_i5.SignUpResponse>);

  @override
  _i15.Future<_i6.LoginResponse> login({required _i21.LoginRequest? request}) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#request: request}),
            returnValue: _i15.Future<_i6.LoginResponse>.value(
              _FakeLoginResponse_4(
                this,
                Invocation.method(#login, [], {#request: request}),
              ),
            ),
          )
          as _i15.Future<_i6.LoginResponse>);

  @override
  _i15.Future<_i4.HttpResponse<_i22.ForgetPasswordResponseDto>> forgetPassword({
    required _i23.ForgetPasswordRequestDto? forgetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [], {
              #forgetPasswordRequestDto: forgetPasswordRequestDto,
            }),
            returnValue:
                _i15.Future<
                  _i4.HttpResponse<_i22.ForgetPasswordResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i22.ForgetPasswordResponseDto>(
                    this,
                    Invocation.method(#forgetPassword, [], {
                      #forgetPasswordRequestDto: forgetPasswordRequestDto,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i22.ForgetPasswordResponseDto>>);

  @override
  _i15.Future<_i4.HttpResponse<_i24.VerifyResetCodeResponseDto>>
  verifyResetCode({
    required _i25.VerifyResetCodeRequestDto? verifyResetCodeRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyResetCode, [], {
              #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
            }),
            returnValue:
                _i15.Future<
                  _i4.HttpResponse<_i24.VerifyResetCodeResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i24.VerifyResetCodeResponseDto>(
                    this,
                    Invocation.method(#verifyResetCode, [], {
                      #verifyResetCodeRequestDto: verifyResetCodeRequestDto,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i24.VerifyResetCodeResponseDto>>);

  @override
  _i15.Future<_i4.HttpResponse<_i26.ResetPasswordResponseDto>> resetPassword({
    required _i27.ResetPasswordRequestDto? resetPasswordRequestDto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #resetPasswordRequestDto: resetPasswordRequestDto,
            }),
            returnValue:
                _i15.Future<
                  _i4.HttpResponse<_i26.ResetPasswordResponseDto>
                >.value(
                  _FakeHttpResponse_2<_i26.ResetPasswordResponseDto>(
                    this,
                    Invocation.method(#resetPassword, [], {
                      #resetPasswordRequestDto: resetPasswordRequestDto,
                    }),
                  ),
                ),
          )
          as _i15.Future<_i4.HttpResponse<_i26.ResetPasswordResponseDto>>);

  @override
  _i15.Future<_i7.CategoriesResponse> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i15.Future<_i7.CategoriesResponse>.value(
              _FakeCategoriesResponse_5(
                this,
                Invocation.method(#getAllCategories, []),
              ),
            ),
          )
          as _i15.Future<_i7.CategoriesResponse>);

  @override
  _i15.Future<_i3.ProductsResponse> getProductsByIdF(
    Map<String, dynamic>? filters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByIdF, [filters]),
            returnValue: _i15.Future<_i3.ProductsResponse>.value(
              _FakeProductsResponse_1(
                this,
                Invocation.method(#getProductsByIdF, [filters]),
              ),
            ),
          )
          as _i15.Future<_i3.ProductsResponse>);

  @override
  _i15.Future<_i8.GetLoggedUserDataResponseDto> getLoggedUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getLoggedUserData, []),
            returnValue: _i15.Future<_i8.GetLoggedUserDataResponseDto>.value(
              _FakeGetLoggedUserDataResponseDto_6(
                this,
                Invocation.method(#getLoggedUserData, []),
              ),
            ),
          )
          as _i15.Future<_i8.GetLoggedUserDataResponseDto>);

  @override
  _i15.Future<_i9.ChangePasswordResponseDto> changePassword(
    _i28.ChangePasswordRequestBody? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [request]),
            returnValue: _i15.Future<_i9.ChangePasswordResponseDto>.value(
              _FakeChangePasswordResponseDto_7(
                this,
                Invocation.method(#changePassword, [request]),
              ),
            ),
          )
          as _i15.Future<_i9.ChangePasswordResponseDto>);

  @override
  _i15.Future<_i10.UpdateProfileResponseDto> editProfile(
    _i29.UpdateProfileRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [request]),
            returnValue: _i15.Future<_i10.UpdateProfileResponseDto>.value(
              _FakeUpdateProfileResponseDto_8(
                this,
                Invocation.method(#editProfile, [request]),
              ),
            ),
          )
          as _i15.Future<_i10.UpdateProfileResponseDto>);

  @override
  _i15.Future<_i11.UpdatePhotoResponseDto> changePhoto(_i30.File? photo) =>
      (super.noSuchMethod(
            Invocation.method(#changePhoto, [photo]),
            returnValue: _i15.Future<_i11.UpdatePhotoResponseDto>.value(
              _FakeUpdatePhotoResponseDto_9(
                this,
                Invocation.method(#changePhoto, [photo]),
              ),
            ),
          )
          as _i15.Future<_i11.UpdatePhotoResponseDto>);

  @override
  _i15.Future<_i12.GetAllNotificationResponseDto> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i15.Future<_i12.GetAllNotificationResponseDto>.value(
              _FakeGetAllNotificationResponseDto_10(
                this,
                Invocation.method(#getNotifications, []),
              ),
            ),
          )
          as _i15.Future<_i12.GetAllNotificationResponseDto>);

  @override
  _i15.Future<_i13.AddressResponseDto> addAddresses(
    _i31.AddAddressRequestDto? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addAddresses, [request]),
            returnValue: _i15.Future<_i13.AddressResponseDto>.value(
              _FakeAddressResponseDto_11(
                this,
                Invocation.method(#addAddresses, [request]),
              ),
            ),
          )
          as _i15.Future<_i13.AddressResponseDto>);

  @override
  _i15.Future<_i13.AddressResponseDto> getAllAddresses() =>
      (super.noSuchMethod(
            Invocation.method(#getAllAddresses, []),
            returnValue: _i15.Future<_i13.AddressResponseDto>.value(
              _FakeAddressResponseDto_11(
                this,
                Invocation.method(#getAllAddresses, []),
              ),
            ),
          )
          as _i15.Future<_i13.AddressResponseDto>);
}
