// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/project_layers/presentation_layer/home/Tabs/category_tab/cubit/category_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/core/api_result/api_result.dart' as _i6;
import 'package:flower_app/project_layers/domain_layer/entities/category_entity.dart'
    as _i7;
import 'package:flower_app/project_layers/domain_layer/entities/product_entity.dart'
    as _i10;
import 'package:flower_app/project_layers/domain_layer/repo/category_repo.dart'
    as _i2;
import 'package:flower_app/project_layers/domain_layer/repo/product_repo.dart'
    as _i3;
import 'package:flower_app/project_layers/domain_layer/usecase/category_use_case.dart'
    as _i4;
import 'package:flower_app/project_layers/domain_layer/usecase/product_use_case.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryRepo_0 extends _i1.SmartFake implements _i2.CategoryRepo {
  _FakeCategoryRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductRepo_1 extends _i1.SmartFake implements _i3.ProductRepo {
  _FakeProductRepo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CategoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryUseCase extends _i1.Mock implements _i4.CategoryUseCase {
  MockCategoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepo get categoryRepo =>
      (super.noSuchMethod(
            Invocation.getter(#categoryRepo),
            returnValue: _FakeCategoryRepo_0(
              this,
              Invocation.getter(#categoryRepo),
            ),
          )
          as _i2.CategoryRepo);

  @override
  set categoryRepo(_i2.CategoryRepo? _categoryRepo) => super.noSuchMethod(
    Invocation.setter(#categoryRepo, _categoryRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i6.ApiResult<List<_i7.CategoryEntity>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<_i6.ApiResult<List<_i7.CategoryEntity>>>.value(
                  _i8.dummyValue<_i6.ApiResult<List<_i7.CategoryEntity>>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i5.Future<_i6.ApiResult<List<_i7.CategoryEntity>>>);
}

/// A class which mocks [ProductUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductUseCase extends _i1.Mock implements _i9.ProductUseCase {
  MockProductUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ProductRepo get productRepo =>
      (super.noSuchMethod(
            Invocation.getter(#productRepo),
            returnValue: _FakeProductRepo_1(
              this,
              Invocation.getter(#productRepo),
            ),
          )
          as _i3.ProductRepo);

  @override
  set productRepo(_i3.ProductRepo? _productRepo) => super.noSuchMethod(
    Invocation.setter(#productRepo, _productRepo),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i6.ApiResult<List<_i10.ProductEntity>>> call(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [categoryId]),
            returnValue:
                _i5.Future<_i6.ApiResult<List<_i10.ProductEntity>>>.value(
                  _i8.dummyValue<_i6.ApiResult<List<_i10.ProductEntity>>>(
                    this,
                    Invocation.method(#call, [categoryId]),
                  ),
                ),
          )
          as _i5.Future<_i6.ApiResult<List<_i10.ProductEntity>>>);
}
